{% set name = "sphinx-togglebutton" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 04c332692fd5f5363ad02a001e693369767d6c1f0e58279770a2aeb571b472a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils
    - python >=3.6
    - sphinx

test:
  imports:
    - sphinx_togglebutton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-togglebutton
  summary: Add a toggle button to items on a page.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
