{% set name = "sphinx-togglebutton" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-togglebutton-{{ version }}.tar.gz
  sha256: 1f13c25c27a8ff40d6fc924d324746c0adb0dedeef40730c8a8b64ff55c6c92c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils
    - python >=3.6
    - sphinx

test:
  imports:
    - sphinx_togglebutton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-togglebutton
  summary: Add a toggle button to items on a page.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
